### ISSUE TITLE
error: control reaches end of non-void function

### ISSUE THREAD

**Issue by Pax-nl** [Simons102/LDTool#1]
First of all thank you for creating and sharing this code. I used your code to encrypt the character data in my own project, but when I tested LegoDimensionsTool.ino there is an issue with the `prepareChip` function, I use PlatformIO and when you use it with the Arduino framework there is an error as this function does not always return 'something'

`src/main.cpp:165:1: error: control reaches end of non-void function [-Werror=return-type]`

```c++ 
bool prepareChip(){
  if(!waitForChip()){
    return false;
  }
  if(!verifyCorrectChip()){
    Serial.println("unknown chip");
    return false;
  }
}
```

(PlatformIO is more picky about the order in your code, you either have to declare all the functions on top or make sure when calling a function the function is on top of the code from where you calling it.
example: `src/main.cpp:234:11: error: 'auth' was not declared in this scope; did you mean 'auto'?`)

**Comment by Simons102** [comment]
Hey, it makes me happy that someone is actually getting some use out of my crappy code :)
It's kind of weird, that the thing ever worked at all. Somehow I must have been lucky enough to have that return value initialised as `true`.
I have since added the offending missing return statement and function definitions to `LegoDimensionsTool.ino`; hopefully that should make it possible to compile everything with PlatformIO.
By the way: if you want to have code blocks, you need to use triple backticks. You can optionally write the language you used after the first triple backticks as a hint for syntax highlighting.
So this:
````
```c++
bool prepareChip(){
  if(!waitForChip()){
    return false;
  }
  if(!verifyCorrectChip()){
    Serial.println("unknown chip");
    return false;
  }
  return true;
}
```
````
would be rendered like this:
```c++
bool prepareChip(){
  if(!waitForChip()){
    return false;
  }
  if(!verifyCorrectChip()){
    Serial.println("unknown chip");
    return false;
  }
  return true;
}
```

**Comment by Pax-nl** [comment]
Thanks updated the comment, ```c++ works..

When my `crappy code` is finished I will publish and mention your repo for the encryption I used. 

Again thank you for this not so crappy code as you think.

**Comment by Simons102** [comment]
Thanks!
I'm looking forward to see what kind of cool stuff you come up with :)
